### ISSUE TITLE
LittleFS data missing

### ISSUE THREAD

**Issue by m4ks84** [khoih-prog/Timezone_Generic#7] opened 2022-06-15 15:20 UTC
Hi,

Thank you for your work.
I have an issue with the releases > V1.7.2
I use LittleFS and with these releases the files in the filesystem are missing. 
There is no compilation error.
Is there something to add since the V1.7.3 in relation with filesystem (i didn't find the solution in examples) ?
 
My project is big so this is an extract of the Timezone code : 
```
// ----------- Timezone parameters ------------
// TimeChangeRules Objet :
TimeChangeRule CEST = {"CEST", Last, Sun, Mar, 2, 120};  // Daylight time = UTC + 2 hours
TimeChangeRule CET = {"CET", Last, Sun, Oct, 3, 60};     // Standard time = UTC + 1 hours
TimeChangeRule *tcr;                                     // Pointer to the time change rule
// Timezone Objet :
Timezone CentralEuroTZ(CEST,CET);`
```
The others instructions in my code are tests (check if current time is DST) so i think it's useless to detail them.

Thanks for your help.

### Information
* Arduino IDE V1.8.19
* ESP8266 : Wemos D1 mini pro V2.0.0 [https://www.wemos.cc/en/latest/d1/d1_mini_pro.html](url)

**Comment by khoih-prog** [comment] 2022-06-16 06:28
Hi @m4ks84 

There is nothing changed relating to ESP8266 and/or LittleFS by this library.

The possible reason is the new and recent ESSP8266 cores have many breaking changes relating to SPIFFS/LittleFS.

Read carefully [**ESP8266 Releases**](https://github.com/esp8266/Arduino/releases), and try old cores (such as **v2.7.4**) and see if OK.

I'm closing the issue now as this is not a bug or issue of this library.

Good Luck,

**Closed as completed by khoih-prog** 2022-06-16 06:28 UTC
Labels: Support
